### ISSUE TITLE
where is the detail code for SQL generating by PCFG?

### ISSUE THREAD

**Issue by DHms2020** [berlino/tensor2struct-public#14]
Hi
Thanks for the source code. but i'm a little confused about where the detail code for SQL generating by PCFG in the papper "Learning to Synthesize Data for Semantic Parsing".
I found the guideline in readme.md mainly focus  on the sql2nl
I'm doing some experiment about generating some code having different grammar with SQL, your method with PCFG inspire me a lot, could you explain how can we get the new SQL by PCFG, i mean the source code. Thanks!!

**Comment by berlino** [comment]
ehmm I'm not entirely sure about your question.

So the PCFG file is here https://github.com/berlino/tensor2struct-public/blob/main/tensor2struct/utils/pcfg.py, and you can take a look at this script https://github.com/berlino/tensor2struct-public/blob/main/experiments/sql2nl/scripts/collect_spider_src_tgt.py to see how to use it to generate new SQL.
