### ISSUE TITLE
Perhaps a bug in the code

### ISSUE THREAD

**Issue by 1160300911** [berlino/tensor2struct-public#15]
Hi, @berlino 

In `tensor2struct/languages/ast/spider.py`, line 253. Should `if not infer_from_conditions` be `if infer_from_conditions`?

Looking forward to your reply, thanks.

**Comment by berlino** [comment]
I don't think so. Infer_from_conditions means you don't need to predict the From clause, implying that the From clause does not need to be predicted (set to None during training)

**Comment by 1160300911** [comment]
I get it, thanks!
