### ISSUE TITLE
ERROR: Saving directory (...tensor2struct-public/.vector_cache/bert-base-multilingual-uncased) should be a directory

### ISSUE THREAD

**Issue by szj2ys** [berlino/tensor2struct-public#16]
when I process spider like this: tensor2struct preprocess configs/spider/run_config/run_ch_spider_bert_baseline.jsonnet

and then I received this error:
```
ERROR: Saving directory (...tensor2struct-public/.vector_cache/bert-base-multilingual-uncased) should be a directory
```
please tell me how can I solve this problem, thanks!

**Comment by berlino** [comment]
ehmm it seems that bert-base-multilingual-uncased is not loaded successfully.   Can you paste all the log here? I can take a look
