### ISSUE TITLE
Problem with synthetic data having JOIN

### ISSUE THREAD

**Issue by duyvuleo** [berlino/tensor2struct-public#2]
Hi there,

Thanks for your great work. 

I was looking at synthetic data (https://github.com/berlino/tensor2struct-public/tree/main/experiments/sql2nl/data-spider-with-ssp-synthetic) and found that:

For utterances with JOIN, e.g., 
**Original**: SELECT * FROM Courses JOIN Student_Course_Registrations ON course_id = course_id

It should be with table aliases, e.g.,
**Expected**: 
SELECT * FROM Courses as T1 JOIN Student_Course_Registrations as T2 ON T1.course_id = T2.course_id
or 
SELECT * FROM Courses JOIN Student_Course_Registrations ON Courses.course_id = Student_Course_Registrations.course_id

Otherwise, the Spider package cannot parse the original SQL query. 

BTW, it would be great if you could also provide the code for synthetic data generator so that ppl can run by themselves?

Thanks!

**Comment by berlino** [comment]
Hi, thanks for your interests!

Somehow tensor2struct's internal representation of SQL does not requires alias, that's why I didn't convert them to the Spider format.

The code for synthesizing is already there actually, I'm planning to add more instructions on how to run them (after some deadline of mine, hopefully within two or three weeks)

**Comment by duyvuleo** [comment]
I was looking for the code of synthesizing but did not find it. @berlino Can you point me to it?

**Comment by yiyunzhao** [comment]
Hi, thanks for the cool work! I am also looking forward to the instructions to run the synthetic data generator.

**Comment by berlino** [comment]
Hi, @duyvuleo @yiyunzhao  

Sorry for the long wait!   I've updated the instructions for reproducing the synthesized data. 

There are many small steps, and it's very likely that I missed some details. Please let me if you have any problem.

Thanks
Bailin

**Comment by berlino** [comment]
Feel free to reopen this issue.
