### ISSUE TITLE
cannot import name 'data_scheduler' from 'experiments.sql2nl'

### ISSUE THREAD

**Issue by hzg456** [berlino/tensor2struct-public#3]
`tensor2struct-public/experiments/sql2nl/__init__.py", line 1, in <module>
    from experiments.sql2nl import data_scheduler
ImportError: cannot import name 'data_scheduler' from 'experiments.sql2nl'`
I want to run the code for "Learning from Executions for Semantic Parsing", and run the instruction `tensor2struct preprocess configs/overnight/run_config/run_overnight_supervised.jsonnet` ,but it failed.
Could you please tell me how to solve it?
Thx！

**Comment by berlino** [comment]
Hi!

I've commented out that line. You can try again to see if the issue is resolved.

**Comment by hzg456** [comment]
OK ！ thx！
